### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by smaragdus** [daramkun/DaramRenamer#10]
Please add an option in "Settings" to use the old toolbar of [Daram Renamer](https://github.com/daramkun/DaramRenamer) as it was in version [3.200](https://github.com/daramkun/DaramRenamer/releases/tag/3.200):

**Daram Renamer** version **3.200** - _toolbar_
![daram renamer 3 200 - 2018-05-10 - toolbar - 001](https://user-images.githubusercontent.com/9025757/39866796-c51eda6c-545a-11e8-82e2-8c08a20dcfc7.png)

the new monochrome one introduced in version [3.300](https://github.com/daramkun/DaramRenamer/releases/tag/3.300):

**Daram Renamer** version **3.400** - _toolbar_
![daram renamer 3 400 - 2018-05-10 - toolbar - 001](https://user-images.githubusercontent.com/9025757/39866666-33ba53ee-545a-11e8-94a7-76d2ff02c658.png)

is too bland and dull for me.

I suppose that other users may also like the old toolbar more.

**Comment by Stefanoko** [comment]
The old toolbar was so much better. The colored icons made it easy to immediately spot functions and tell them apart. The new black and white look, however, is difficult to operate, it appears crammed and narrow, almost like text, tedious to read and not inviting.

**Comment by smaragdus** [comment]
@daramkun 
You are the developer and you decide but I am disappointed- I like **Daram Renamer** but I will have to stick to version [3.200](https://github.com/daramkun/DaramRenamer/releases/tag/3.200)- for me it is not just a matter of personal preferences and tastes but about visibility as well- for me the old colourful icons are easier to see and remember while the new monochrome ones are smaller and harder to discern. **Daram Renamer** is less than 1 MB so at least for me a few KB less or more don't make great difference.

**Off-topic**
Since I liked Daram Renamer I wrote a short review about it at [The Portable Freeware Forum](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=24192). I hope I didn't miss something important.

**Comment by daramkun** [comment]
OK, When I have a time, I will try develop this option.

**Comment by smaragdus** [comment]
@daramkun 
I will be very grateful!

**Comment by daramkun** [comment]
**Default Icon**
![image](https://user-images.githubusercontent.com/1378304/40037164-ac3a6de6-5846-11e8-85f0-370ffbd28717.png)

**Apply ToolBar Icon Pack**
![image](https://user-images.githubusercontent.com/1378304/40037153-9e9b9868-5846-11e8-9259-bdd2b4ddd5d9.png)

**Comment by smaragdus** [comment]
@daramkun 
This is exactly what I wanted, thanks!

**Comment by smaragdus** [comment]
@daramkun 
I [notified](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=24192&p=90531#p90531) The Portable Freeware community about the new version (**3.500**) of **Daram Renamer**.

**Comment by smaragdus** [comment]
Your implementation of using the old toolbar is good and logical- thus only people who really need it will get it as a separate download. Thanks and regards.
