### ISSUE TITLE
Undo / redo process

### ISSUE THREAD

**Issue by vatterspun** [daramkun/DaramRenamer#12]
Thanks to _smaragdus_ for pointing this out to me.  Came across a minor issue

Setup: Win7x86

Steps: 

1. Create some test files (all zero KB in size)
2. Drag and drop into the window
3. Make a change e.g. CaseCast extension "To Upper"

![image](https://user-images.githubusercontent.com/1289134/39961415-14466078-55fb-11e8-89b6-932809972bf9.png)

4. Undo via CTRL+Z to undo (as expected it restores it's previous state)
5. Press CTRL+Y to redo 

Defect: list clears

If you press CTRL+Z and CTRL+Y again, the program will crash

Hope that helps.

**Comment by vatterspun** [comment]
Result?

**Comment by daramkun** [comment]
Undo/Redo bug fixed in Version 3.500(2018-05-15).
