### ISSUE TITLE
[Feature request] Transform list

### ISSUE THREAD

**Issue by vatterspun** [daramkun/DaramRenamer#14]
**Current behavior:**

Click icons and enter information to make changes to original files.  

**Requested capability:**

1. Click icon or screen element to open a view of transformations and enable transformation order change.  For example:

1. Replace text "test" with "eval"
2. Concat text "vehicle" with front, no extention
3. Casecast method: To lower

**Comment by daramkun** [comment]
I tried development this feature for script feature. but this feature makes so complicate codes and design when developing just me alone.
So, I just developed this feature to Batch script with Jint(.NET Javascript Runtime library).

**Comment by vatterspun** [comment]
I acknowledge this is a non-simple probably rather tedious request.  Thanks for hearing me out.  For reference here's how the excellent but limited Renamer software handles the process mentioned above:

![image](https://user-images.githubusercontent.com/1289134/39970634-6fa74946-56b4-11e8-9fbb-cc7e52bf963d.png)

**Comment by daramkun** [comment]
This feature implementing to New Daram Renamer. Very basic features implemented into 2020.10.1 Alpha 3 build.

**Comment by daramkun** [comment]
This feature implemented to New DaramRenamer. Load/Save implemented into 2020.10.2 Alpha 4 build.
