### ISSUE TITLE
Daram Renamer 3.700 - crash on start

### ISSUE THREAD

**Issue by smaragdus** [daramkun/DaramRenamer#15]
I updated from version [3.600](https://github.com/daramkun/DaramRenamer/releases/tag/3.600) to version  [3.700](https://github.com/daramkun/DaramRenamer/releases/tag/3.700) and [Daram Renamer](https://github.com/daramkun/DaramRenamer) fails to start, screens:

![daram renamer 3 700 - 2018-09-18 - error - 001](https://user-images.githubusercontent.com/9025757/45695339-e273cc00-bb69-11e8-80d0-55c68ed2bbfa.png)

![daram renamer 3 700 - 2018-09-18 - error - 002](https://user-images.githubusercontent.com/9025757/45695349-e69fe980-bb69-11e8-8932-d559812838ea.png)

error log:

[error.log](https://github.com/daramkun/DaramRenamer/files/2393154/error.log)

This happens under _Windows 8 x64_. **Daram Renamer** version **3.600** is working just fine on my system.

**Comment by daramkun** [comment]
Thanks to your help. I will check this problem.

**Comment by daramkun** [comment]
What is your really OS version? Windows 8? Windows 8.1?

[This article](https://docs.microsoft.com/ko-kr/dotnet/framework/get-started/system-requirements), Windows 8 is not support .NET Framework 4.7.2. Only maximum support to 4.6.1. Windows 8.1 support to 4.7.2.

**Comment by smaragdus** [comment]
@daramkun 

I had the impression that the minimum requirement for Daram Renamer was .NET 4.6.
I am using Windows 8 so I cannot use .NET 4,7
So I see that this issue is specific to my system only so I will close it,
