### ISSUE TITLE
정규표현식 사용 자체가 안됩니다.

### ISSUE THREAD

**Issue by whiteariel** [daramkun/DaramRenamer#18]
똑같은 파일을 만들어서, 다른 글에 올려주신 예제를 적용해보았으나 반응 자체가 없습니다.

아마 작동 자체가 안되는것 같더라구요.

뭔가 라이브러리 같은걸 못 읽어오는 것 같은데, 어떻게 해야 하나요?

**Comment by daramkun** [comment]
한번 테스트해보고 원인을 찾아보겠습니다

**Comment by daramkun** [comment]
3.760 버전에서 해결됐습니다.
