### ISSUE TITLE
일괄처리 기능 예제가 있을까요?

### ISSUE THREAD

**Issue by whiteariel** [daramkun/DaramRenamer#19]
제가 일괄처리 기능을 사용해보고 싶어서 해봤는데 에러코드가 발생하더군요.

!replace:"도레미" "미레도"

이렇게 넣으니 아래와 같은 에러가 발생합니다.

Error: 2019-06-16 01-35-49 - from Daram Renamer
----
System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.IO.FileNotFoundException: 파일이나 어셈블리 'DaramRenamer.Engine' 또는 여기에 종속되어 있는 파일이나 어셈블리 중 하나를 로드할 수 없습니다. 지정된 파일을 찾을 수 없습니다.
   위치: System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   위치: System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   위치: System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   위치: System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   위치: System.Reflection.Assembly.Load(String assemblyString)
   위치: Daramkun.DaramRenamer.ProcessorExtensions.get_Delegates()
   위치: Daramkun.DaramRenamer.Processors.BatchProcessor.Process(FileInfo file)
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   위치: System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   위치: System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   위치: System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   위치: Daramkun.DaramRenamer.MainWindow.ClosePopup(Boolean apply)
   위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   위치: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   위치: System.Windows.Controls.Primitives.ButtonBase.OnClick()
   위치: System.Windows.Controls.Button.OnClick()
   위치: System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   위치: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   위치: System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   위치: System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   위치: System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   위치: System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   위치: System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   위치: System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   위치: System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   위치: System.Windows.Input.InputManager.ProcessStagingArea()
   위치: System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   위치: System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   위치: System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   위치: System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   위치: System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   위치: MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   위치: MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   위치: System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   위치: System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   위치: System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   위치: MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   위치: MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   위치: System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   위치: System.Windows.Application.RunDispatcher(Object ignore)
   위치: System.Windows.Application.RunInternal(Window window)
   위치: Daramkun.DaramRenamer.App.Main()
---> (내부 예외 #0) System.IO.FileNotFoundException: 파일이나 어셈블리 'DaramRenamer.Engine' 또는 여기에 종속되어 있는 파일이나 어셈블리 중 하나를 로드할 수 없습니다. 지정된 파일을 찾을 수 없습니다.
파일 이름: 'DaramRenamer.Engine'
   위치: System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   위치: System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   위치: System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   위치: System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   위치: System.Reflection.Assembly.Load(String assemblyString)
   위치: Daramkun.DaramRenamer.ProcessorExtensions.get_Delegates()
   위치: Daramkun.DaramRenamer.Processors.BatchProcessor.Process(FileInfo file)
   위치: System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   위치: System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   위치: System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)

경고: 어셈블리 바인딩 로깅이 꺼져 있습니다.
어셈블리 바인딩 오류 로깅 기능을 사용하려면 레지스트리 값 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)를 1로 설정하십시오.
참고: 어셈블리 바인딩 오류 로깅 기능을 사용하도록 설정하면 그렇지 않은 경우보다 성능이 약간 떨어집니다.
이 기능을 끄려면 레지스트리 값 [HKLM\Software\Microsoft\Fusion!EnableLog]를 제거하십시오.
<---

==========================================================

뭔가 로딩이 안되는 듯 하여, 글 남깁니다.

좋은 프로그램 잘 사용하고 있습니다.^^

**Comment by daramkun** [comment]
해당 문법은 현재 버전에서 안 먹히는 것은 차치하고라도(자바스크립트로 바뀌었습니다) 현 문법으로도 오류가 나는걸 보니 문제가 있는 것 같아서 확인해보겠습니다

**Comment by whiteariel** [comment]
감사합니다. 그럼 현 문법으로는 어떻게 사용하는지 예제라도 알려주실 수 있을까요?

**Comment by daramkun** [comment]
예를 들어 모든 파일의 이름을 지우는 함수는 process_delete_text 라는 이름으로, 모든 함수의 첫번째 인자에는 fileInfo가 반드시 들어갑니다. process_delete_text 함수의 인자는 없으므로 process_delete_text(fileInfo)로 실행됩니다.

문자열 치환 함수는 process_replace_plain_text로, 세 인자가 들어갑니다. 원본 문자열, 바꿀 문자열, 확장자 포함 여부이므로 process_replace_plain_text (fileInfo, "원본", "치환", false) 와 같은 형태로 호출하면 됩니다.

**Comment by daramkun** [comment]
3.770 버전에서 수정했습니다. 자세한 사용법은 시간날 때 위키에 추가해보도록 하겠습니다.

**Comment by whiteariel** [comment]
네 감사합니다~
