### ISSUE TITLE
두가지 사항을 제안드리고 싶습니다.

### ISSUE THREAD

**Issue by whiteariel** [daramkun/DaramRenamer#21]
이 프로그램을 정말 잘 쓰고 있습니다.

알파 버전으로 올라온 리뉴얼 버전도 많이 편해서 좋네요.

첫번째 기능은 폴더 이름을 받아오는 기능입니다.

폴더 이름을 파일명으로 받아오고, 그러고 나서 뒤에 번호를 붙이려고 하는데

이를 수작업으로 하려니 조금 번거로워서요.

참고로 알씨 일괄이름 바꾸기에서 지원하는 기능인데,

다람 리네이머에서도 지원해주면 좋겠다는 생각이 들어서 제안하게 되었습니다.

두번째는 단축키 기능입니다.

너무 기본적인 단축키 기능만 지원해서 조금 더 다양한 단축키를 지원했으면 하는 바램입니다.

아니면 사용자가 단축키를 설정할 수 있는 기능이어도 좋겠습니다.

정말 잘 쓰고 있어서 제작자님께 감사하다는 말씀을 이 글을 빌어 전하고 싶습니다.

감사합니다.

**Comment by daramkun** [comment]
두 기능 모두 개발 고려해보겠습니다. 의견 감사합니다.

**Comment by daramkun** [comment]
첫번째 기능 파일로부터 파일명 목록을 읽어오는 거라고 생각했는데 다시 보니 목록에 폴더 추가군요. 폴더를 드래그 해오면 폴더 추가가 가능합니다. 다만 파일 말고도 폴더를 여는 메뉴도 추가하겠습니다
