### ISSUE TITLE
약간의 소통 문제가 있었던 듯 해서 다시 제안드립니다.

### ISSUE THREAD

**Issue by whiteariel** [daramkun/DaramRenamer#22]
지난번에 폴더 이름 받아오는 문제로 말씀드린 사람입니다.

폴더가 드래그로 등록이 되는건 알고 있던 사항이었구요, 그게 아니라 다른 걸 제안드린 건데 제 설명이 부족했던 모양이네요.

예를 들어서 /리네이머/폴더의 파일 중 '사람.ext'의 파일 이름 '리네이머-사람.ext'로 바꾸고 싶은 상황입니다.

이때 앞에 붙는 '리네이머'는 파일이 속한 폴더명입니다.

이 기능을 넣어주시는게 가능하신가 해서 여쭤봤었습니다.

혹시 가능한 문제일까요?

**Comment by daramkun** [comment]
이 기능은 구현에 시간이 좀 걸릴 것 같습니다. 아마 정식 버전 공개 이후에 구현이 가능할 것 같네요.

**Comment by daramkun** [comment]
@whiteariel 폴더 이름을 파일명에 추가할 수 있는 기능 `2021.5.2` 버전에 추가했습니다.
