### ISSUE TITLE
영문으로 바꿀 시 동작이 이상합니다

### ISSUE THREAD

**Issue by whiteariel** [daramkun/DaramRenamer#25]
기본인 한글에서는 정상적으로 이름 바꾸기가 동작하는데

영문판에서는 같은 파일이 이름 바꿔서 하나 더 생성되고, 기존의 것은 남네요

**Comment by daramkun** [comment]
퇴근 후 한번 확인해보겠습니다.

**Comment by whiteariel** [comment]
네 감사합니다 ^^

**Comment by daramkun** [comment]
원인 확인해서 수정했습니다
