### ISSUE TITLE
v2022.1.1 only in Korean language?

### ISSUE THREAD

**Issue by Stephan-P** [daramkun/DaramRenamer#31]
DaramRenamer opens in Korean language, which I do not understand.
Manually editing the config.json did not make a change to this.
With some effort I managed to wade through the Korean menu to find the language option.
After selecting English or Dutch language everything is fine.

**Comment by daramkun** [comment]
This is fixed in version `2022.1.2` but I'm not sure. Tested on Windows 10 English only.

**Comment by Stephan-P** [comment]
Tested and confirmed to be fixed.
I ensured that the config.json created by version 2022.1.1 was no longer in place and v2022.1.2 automatically started in Dutch language.
Thanks
