### ISSUE TITLE
정규 표현식 사용시 패턴 적중 여부 없이 모든 파일에 적용됨.

### ISSUE THREAD

**Issue by rhdtl78** [daramkun/DaramRenamer#8]
예를 들어 괄호 포함, 괄호 사이의 6~7자의 숫자만 제거하는 정규표현식이
\([0-9]{6,7}\) 인데 이걸 모두 지우게끔 하면 이것과 맞지 않는 모든 파일까지 전부 이름이 통으로 지워집니다.

혹시 제가 잘못 사용하고 있는지 확인하고 싶군요
정규표현식 란에 제가 매칭하고싶은 패턴이 들어가고 
구성 형식문자열에 제가 만들고싶은 내용이 들어가면 되나요

**Comment by daramkun** [comment]
처음에 제가 고려했던 정규표현식 파일명 치환 기능은 정규표현식을 통해 그룹을 추출한 뒤 이 그룹을 가지고 C# 형식문자열 기능을 통해 추출한 그룹 텍스트를 적용할 수 있는 기능입니다.

**"abcd - 01.mp4"** 라는 파일명이 있다면
**"(.*) - ([0-9]+)"**라는 정규표현식으로 추출한 뒤
**"{1} - {0}"**이라는 C# 형식문자열을 이용해 파일명을 치환하면 
**"01 - abcd.mp4"**라는 파일명이 완성되는 형식입니다.

이 기능이 아닌 말씀하신 정규표현식에 해당하는 문자열만 다른 문자열로 치환하는 기능이 필요하시면 한번 추가를 해보겠습니다.

**Comment by rhdtl78** [comment]
오 그 기능이 추가된다면 정말 좋겠습니다. 이슈는 닫지 않겠습니다. ㅎ 
기대하고 있겠습니다.

**Comment by daramkun** [comment]
3.4 버전에서 기능 추가했습니다
